[ImagePath]
Board = "%HOME%/サンプル画像/チェス系/チェス盤.png"
WR = "%HOME%/サンプル画像/チェス系/wr.png"
WN = "%HOME%/サンプル画像/チェス系/wn.png"
WB = "%HOME%/サンプル画像/チェス系/wb.png"
WQ = "%HOME%/サンプル画像/チェス系/wq.png"
WK = "%HOME%/サンプル画像/チェス系/wk.png"
WP = "%HOME%/サンプル画像/チェス系/wp.png"
BP = "%HOME%/サンプル画像/チェス系/bP.png"
BR = "%HOME%/サンプル画像/チェス系/bR.png"
BN = "%HOME%/サンプル画像/チェス系/bN.png"
BB = "%HOME%/サンプル画像/チェス系/bB.png"
BQ = "%HOME%/サンプル画像/チェス系/bQ.png"
BK = "%HOME%/サンプル画像/チェス系/bK.png"
