[ImagePath]
GroundWood = "%HOME%/サンプル画像/01_b_碁石（小）/groundWood.png"
GroundBlack = "%HOME%/サンプル画像/01_b_碁石（小）/groundBlack.png"
GroundWhite = "%HOME%/サンプル画像/01_b_碁石（小）/groundWhite.png"
GroundGreen = "%HOME%/サンプル画像/01_b_碁石（小）/groundGreen.png"
Roban5 = "%HOME%/サンプル画像/01_b_碁石（小）/大きな画像/5路盤（罫線）.png"
EmptyA1 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA1┌.png"
EmptyA2 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA2┬.png"
EmptyA3 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA3┐.png"
EmptyA4 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA4├.png"
EmptyA5 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA5┼.png"
EmptyA6 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA6┤.png"
EmptyA7 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA7└.png"
EmptyA8 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA8┴.png"
EmptyA9 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyA9┘.png"
BlackStone = "%HOME%/サンプル画像/01_b_碁石（小）/blackStone.png"
WhiteStone = "%HOME%/サンプル画像/01_b_碁石（小）/whiteStone.png"
BlackCaptured = "%HOME%/サンプル画像/01_b_碁石（小）/blackCaptured.png"
WhiteCaptured = "%HOME%/サンプル画像/01_b_碁石（小）/whiteCaptured.png"
EmptyB1 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB1┌.png"
EmptyB2 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB2┬.png"
EmptyB3 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB3┐.png"
EmptyB4 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB4├.png"
EmptyB5 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB5┼.png"
EmptyB6 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB6┤.png"
EmptyB7 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB7└.png"
EmptyB8 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB8┴.png"
EmptyB9 = "%HOME%/サンプル画像/01_b_碁石（小）/emptyB9┘.png"
B1 = "%HOME%/サンプル画像/01_b_碁石（小）/b1.png"
B2 = "%HOME%/サンプル画像/01_b_碁石（小）/b2.png"
MarkerDead = "%HOME%/サンプル画像/01_b_碁石（小）/markerDead.png"
MarkerDropped = "%HOME%/サンプル画像/01_b_碁石（小）/markerDropped.png"
B3 = "%HOME%/サンプル画像/01_b_碁石（小）/b3.png"
B4 = "%HOME%/サンプル画像/01_b_碁石（小）/b4.png"
B5 = "%HOME%/サンプル画像/01_b_碁石（小）/b5.png"
B6 = "%HOME%/サンプル画像/01_b_碁石（小）/b6.png"
B7 = "%HOME%/サンプル画像/01_b_碁石（小）/b7.png"
B8 = "%HOME%/サンプル画像/01_b_碁石（小）/b8.png"
B9 = "%HOME%/サンプル画像/01_b_碁石（小）/b9.png"
B10 = "%HOME%/サンプル画像/01_b_碁石（小）/b10.png"
